---
- hosts:
    stuff
  name:
    Deploy sqrt26

  vars:
    deps:
      apt:
        - haproxy
        - jekyll
    repo:
      url:
        https://github.com/femnad/sqrt26.com.git
    user_service:
      description:
        Jekyll server for sqrt26.com
      name:
        jekyll-sqrt26
      exec:
        /usr/bin/jekyll serve -s {{ source.path }}/jekyll -d {{ source.path }}/jekyll/_site

  roles:
    - packages
    - clone
    - systemd_user_service

- import_playbook:
    configure_haproxy.yaml
  tags:
    haproxy
